[versions]
about-libraries = "11.2.3"
activity-compose = "1.9.3"
android-gradle = "8.7.2"
android-lifecycle-compose = "2.8.7"
android-preferences = "1.2.1"
android-test-runner = "1.6.2"
android-test-junit = "1.2.1"
compose = "1.7.1"
compose-material3 = "1.3.1"
compose-navigation = "2.8.0-alpha10"
coroutines = "1.9.0"
datastore = "1.1.1"
datetime = "0.6.1"
detekt = "1.23.7"
emojipicker = "1.5.0"
io = "0.5.4"
junit = "4.13.2"
koin = "4.0.0"
kotlin = "2.0.21"
kover = "0.8.3"
ktor = "3.0.1"
paging = "3.3.0-alpha02-0.5.1"
paging-android = "3.3.4"
serialization-json = "1.7.3"
serialization-csv = "0.0.18"
serialization-yaml = "0.13.0"
shimmer = "1.3.1"
sqldelight = "2.0.2"
turbine = "1.2.0"

[libraries]
about-libraries = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "about-libraries" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
androidx-compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
androidx-emojipicker = { module = "androidx.emoji2:emoji2-emojipicker", version.ref = "emojipicker" }
androidx-lifecycle-compose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "android-lifecycle-compose" }
androidx-preferences = { module = "androidx.preference:preference", version.ref = "android-preferences"}
androidx-test-runner = { module = "androidx.test:runner", version.ref = "android-test-runner" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "android-test-junit" }
androidx-test-junit-ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "android-test-junit" }
compose-navigation = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "compose-navigation" }
datastore = { module = "androidx.datastore:datastore-preferences", version.ref = "datastore" }
junit = { module = "junit:junit", version.ref = "junit" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koin" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-compose = { module = "io.insert-koin:koin-compose" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel" }
koin-core = { module = "io.insert-koin:koin-core" }
koin-test = { module = "io.insert-koin:koin-test" }
koin-viewmodel = { module = "io.insert-koin:koin-core-viewmodel" }
kotlinx-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-dateTime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
kotlinx-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "io" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization-json" }
kotlinx-serialization-csv = { module = "app.softwork:kotlinx-serialization-csv", version.ref = "serialization-csv" }
kotlinx-serialization-yaml = { module = "net.mamoe.yamlkt:yamlkt", version.ref = "serialization-yaml" }
ktor-android = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-contentnegotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-mock = { module = "io.ktor:ktor-client-mock", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
paging-android = { module = "androidx.paging:paging-runtime", version.ref = "paging-android" }
paging-android-compose = { module = "androidx.paging:paging-compose", version.ref = "paging-android" }
paging-common = { module = "app.cash.paging:paging-common", version.ref = "paging" }
paging-common-compose = { module = "app.cash.paging:paging-compose-common", version.ref = "paging" }
shimmer = { module = "com.valentinilk.shimmer:compose-shimmer", version.ref = "shimmer" }
sqldelight-android = { module = "app.cash.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-coroutines = { module = "app.cash.sqldelight:coroutines-extensions", version.ref = "sqldelight" }
sqldelight-jvm = { module = "app.cash.sqldelight:sqlite-driver", version.ref = "sqldelight" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }

[plugins]
about-libraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "about-libraries" }
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
sqldelight = { id = "app.cash.sqldelight", version.ref = "sqldelight" }